### ISSUE TITLE
FCF Status ?

### ISSUE THREAD

**Issue by spitters** [adampetcher/fcf#18]
@adampetcher What's the current status of FCF? I see recent additions by @JasonGross, @andres-erbsen and @natelaunchbury.
Are there other projects using FCF?

**Comment by adampetcher** [comment]
I'm still maintaining FCF and happily supporting anyone who wants to use it. I'm not directly involved in any current projects involving FCF, and I don't know whether Jason, Andres, or Nate are still working with FCF.

**Comment by natelaunchbury** [comment]
I actively use FCF for my research and plan to do so for the next few years

**Comment by spitters** [comment]
Thanks. @natelaunchbury could you elaborate on your plans with FCF?
