### ISSUE TITLE
please add an explicit license grant

### ISSUE THREAD

**Issue by andres-erbsen** [adampetcher/fcf#2]
Hello,

I am considering using this library in a project, and I noticed that this repository does not seem to contain any information about copyright/patent licensing. https://github.com/PrincetonUniversity/VST/blob/master/LICENSE says that its imported copy of fcf is released under the 2-clause BSD license. If this is also true for this repository, please

1. Add a corresponding license file into the root directory of the project (e.g., from https://github.com/IQAndreas/markdown-licenses/blob/master/bsd-2.md)
2. Add a short license header to each file (possibly using the 10-line shell script from https://stackoverflow.com/questions/151677/tool-for-adding-license-headers-to-source-files), for example

        (* Copyright 2010 <AUTHOR>.  All rights reserved.
         * Use of this source code is governed by a BSD-style
         * license that can be found in the LICENSE file. *)

3. (patents) if something similar to https://golang.org/PATENTS is true about this project as well, add a corresponding statement to a corresponding file. This is not implied by the BSD-2 license, and some may be comfortable using this code without it, but IMHO it is easier to add the statement (if it is true) than to convince somebody's employer that they don't need it to use the code.

The options I outlined here are almost straight from <http://choosealicense.com/>, you can see there for more information and alternatives.

Thanks,
Andres

**Comment by adampetcher** [comment]
The code is licensed under Apache 2.0 (which should appropriately handle the patent issues).  I added the LICENSE file and marked up all the source files as you suggested.  

Make sure you let me know if I can provide any help or guidance with using FCF in your project.
