### ISSUE TITLE
Namespace pollution

### ISSUE THREAD

**Issue by andres-erbsen** [adampetcher/fcf#3]
Currently, a project using FCF as a module gets all FCF filenames in the root namespace, e.g. 
"Require Import Asymptotic" refers to FCF-s notion of asymptotic, and effectively prevents use of any library of the same name. I think it would make sense to change FCF _Coqproject to `-R . FCF`. In that case importers would need to type "Require Import FCF.Asymptotic". Should I go do it and make a PR?

**Comment by adampetcher** [comment]
That would be great! Thanks!

**Comment by andres-erbsen** [comment]
This happened: https://github.com/adampetcher/fcf/commit/6dd52b77b24b7ff2d6bb1a15a0e4d6e4491593cc
